export default {
  languages: [
    {
      key: 'hiragana',
      language: 'Japanese',
      alphabet: 'Hiragana',
      native: 'ひらがな',
      img: 'japan.svg'
    },
    {
      key: 'katakana',
      language: 'Japanese',
      alphabet: 'Katanaka',
      native: 'カタカナ',
      img: 'japan.svg'
    },
    {
      key: 'hangul',
      language: 'Korean',
      alphabet: 'Hangul',
      native: '한글 ',
      img: 'korea.png'
    }
  ],
  characterMap: {
    hangul: [
      ['ㅏ', 'a'],
      ['ㅐ', 'ae'],
      ['ㅑ', 'ya'],
      ['ㅒ', 'yae'],
      ['ㅓ', 'eo'],
      ['ㅔ', 'e'],
      ['ㅕ', 'yeo'],
      ['ㅖ', 'ye'],
      ['ㅗ', 'o'],
      ['ㅘ', 'wa'],
      ['ㅙ', 'wae'],
      ['ㅚ', 'oe'],
      ['ㅛ', 'yo'],
      ['ㅜ', 'u'],
      ['ㅝ', 'wo'],
      ['ㅞ', 'we'],
      ['ㅟ', 'wi'],
      ['ㅠ', 'yu'],
      ['ㅡ', 'eu'],
      ['ㅢ', 'ui'],
      ['ㅣ', 'i'],
      ['ㄷ', 'd'],
      ['ㄹ', 'r/l'],
      ['ㅁ', 'm'],
      ['ㅂ', 'b'],
      ['ㅅ', 's'],
      ['ㅇ', '-'],
      ['ㅈ', 'j'],
      ['ㅊ', 'ch'],
      ['ㅋ', 'k'],
      ['ㅌ', 't'],
      ['ㅍ', 'p'],
      ['ㅎ', 'h'],
      ['ㄲ', 'kk'],
      ['ㄸ', 'tt'],
      ['ㅃ', 'pp'],
      ['ㅆ', 'ss']
    ],
    katakana: [
      ['ア', 'a'],
      ['イ', 'i'],
      ['ウ', 'u'],
      ['エ', 'e'],
      ['オ', 'o'],
      ['カ', 'ka'],
      ['キ', 'ki'],
      ['ク', 'ku'],
      ['ケ', 'ke'],
      ['コ', 'ko'],
      ['キャ', 'kya'],
      ['キュ', 'kyu'],
      ['キョ', 'kyo'],
      ['サ', 'sa'],
      ['シ', 'shi'],
      ['ス', 'su'],
      ['セ', 'se'],
      ['ソ', 'so'],
      ['シャ', 'sha'],
      ['シュ', 'shu'],
      ['ショ', 'sho'],
      ['タ', 'ta'],
      ['チ', 'chi'],
      ['ツ', 'tsu'],
      ['テ', 'te'],
      ['ト', 'to'],
      ['チャ', 'cha'],
      ['チュ', 'chu'],
      ['チョ', 'cho'],
      ['ナ', 'na'],
      ['ニ', 'ni'],
      ['ヌ', 'nu'],
      ['ネ', 'ne'],
      ['ノ', 'no'],
      ['ニャ', 'nya'],
      ['ニュ', 'nyu'],
      ['ニョ', 'nyo'],
      ['ハ', ' ha'],
      ['ヒ', ' hi'],
      ['フ', ' fu'],
      ['ヘ', ' he'],
      ['ホ', ' ho'],
      ['ヒャ', ' hya'],
      ['ヒュ', ' hyu'],
      ['ヒョ', ' hyo'],
      ['マ', 'ma'],
      ['ミ', 'mi'],
      ['ム', 'mu'],
      ['メ', 'me'],
      ['モ', 'mo'],
      ['ミャ', 'mya'],
      ['ミュ', 'myu'],
      ['ミョ', 'myo'],
      ['ヤ', 'ya'],
      ['ユ', 'yu'],
      ['ヨ', 'yo'],
      ['ラ', 'ra'],
      ['リ', 'ri'],
      ['ル', 'ru'],
      ['レ', 're'],
      ['ロ', 'ro'],
      ['リャ', 'rya'],
      ['リュ', 'ryu'],
      ['リョ', 'ryo'],
      ['ワ', 'wa'],
      ['ヰ', 'wi'],
      ['ヱ', 'we'],
      ['ヲ', 'wo'],
      ['ガ', 'ga'],
      ['ギ', 'gi'],
      ['グ', 'gu'],
      ['ゲ', 'ge'],
      ['ゴ', 'go'],
      ['ギャ', 'gya'],
      ['ギュ', 'gyu'],
      ['ギョ', 'gyo'],
      ['ザ', 'za'],
      ['ジ', 'ji'],
      ['ズ', 'zu'],
      ['ゼ', 'ze'],
      ['ゾ', 'zo'],
      ['ジャ', 'ja'],
      ['ジュ', 'ju'],
      ['ジョ', 'jo'],
      ['ダ', 'da'],
      ['ヂ', 'ji'],
      ['ヅ', 'zu'],
      ['デ', 'de'],
      ['ド', 'do'],
      ['ヂャ', 'ja'],
      ['ヂュ', 'ju'],
      ['ヂョ', 'jo'],
      ['バ', 'ba'],
      ['ビ', 'bi'],
      ['ブ', 'bu'],
      ['ベ', 'be'],
      ['ボ', 'bo'],
      ['ビャ', 'bya'],
      ['ビュ', 'byu'],
      ['ビョ', 'byo'],
      ['パ', 'pa'],
      ['ピ', 'pi'],
      ['プ', 'pu'],
      ['ペ', 'pe'],
      ['ポ', 'po'],
      ['ピャ', 'pya'],
      ['ピュ', 'pyu'],
      ['ピョ', 'pyo']
    ],
    hiragana: [
      ['あ', 'a', 'a'],
      ['か', 'ka', 'ka'],
      ['さ', 'sa', 'sa'],
      ['た', 'ta', 'ta'],
      ['な', 'na', 'na'],
      ['は', 'ha', 'ha'],
      ['ま', 'ma', 'ma'],
      ['や', 'ya', 'ja'],
      ['ら', 'ra', 'ɾa'],
      ['わ', 'wa', 'ɰa'],
      ['い', 'i', 'i'],
      ['き', 'ki', 'ki'],
      ['し', 'shi', 'ɕi'],
      ['ち', 'chi', 'tɕi'],
      ['に', 'ni', 'ɲi'],
      ['ひ', 'hi', 'çi'],
      ['み', 'mi', 'mi'],
      ['り', 'ri', 'ɾi'],
      ['ゐ', 'wi', 'i'],
      ['う', 'u', 'ɯ'],
      ['く', 'ku', 'kɯ'],
      ['す', 'su', 'sɯ'],
      ['つ', 'tsu', 'tsɯ'],
      ['ぬ', 'nu', 'nɯ'],
      ['ふ', 'fu', 'ɸɯ'],
      ['む', 'mu', 'mɯ'],
      ['ゆ', 'yu', 'jɯ'],
      ['る', 'ru', 'ɾɯ'],
      ['え', 'e', 'e'],
      ['け', 'ke', 'ke'],
      ['せ', 'se', 'se'],
      ['て', 'te', 'te'],
      ['ね', 'ne', 'ne'],
      ['へ', 'he', 'he'],
      ['め', 'me', 'me'],
      ['れ', 're', 'ɾe'],
      ['ゑ', 'we', 'e'],
      ['お', 'o', 'o'],
      ['こ', 'ko', 'ko'],
      ['そ', 'so', 'so'],
      ['と', 'to', 'to'],
      ['の', 'no', 'no'],
      ['ほ', 'ho', 'ho'],
      ['も', 'mo', 'mo'],
      ['よ', 'yo', 'jo'],
      ['ろ', 'ro', 'ɾo'],
      ['を', 'wo', 'o'],
      ['が', 'ga', 'ɡa'],
      ['ざ', 'za', 'za'],
      ['だ', 'da', 'da'],
      ['ば', 'ba', 'ba'],
      ['ぱ', 'pa', 'pa'],
      ['ぎ', 'gi', 'ɡi'],
      ['じ', 'ji', 'ʑi'],
      ['ぢ', 'ji', 'dji'],
      ['び', 'bi', 'bi'],
      ['ぴ', 'pi', 'pi'],
      ['ぐ', 'gu', 'ɡɯ'],
      ['ず', 'zu', 'zɯ'],
      ['づ', 'dzu', 'zu'],
      ['ぶ', 'bu', 'bɯ'],
      ['ぷ', 'pu', 'pɯ'],
      ['げ', 'ge', 'ɡe'],
      ['ぜ', 'ze', 'ze'],
      ['で', 'de', 'de'],
      ['べ', 'be', 'be'],
      ['ぺ', 'pe', 'pe'],
      ['ご', 'go', 'ɡo'],
      ['ぞ', 'zo', 'zo'],
      ['ど', 'do', 'do'],
      ['ぼ', 'bo', 'bo'],
      ['ぽ', 'po', 'po'],
      ['ぎゃ', 'gya', 'ɡʲa'],
      ['じゃ', 'ja', 'ʑa'],
      ['ぢゃ', 'ja', 'ʑa'],
      ['びゃ', 'bya', 'bʲa'],
      ['ぴゃ', 'pya', 'pʲa'],
      ['ぎゅ', 'gyu', 'ɡʲɯ'],
      ['じゅ', 'ju', 'ʑɯ'],
      ['ぢゅ', 'ju', 'ʑɯ'],
      ['びゅ', 'byu', 'bʲɯ'],
      ['ぴゅ', 'pyu', 'pʲɯ'],
      ['ぎょ', 'gyo', 'ɡʲo'],
      ['じょ', 'jo', 'ʑo'],
      ['ぢょ', 'jo', 'ʑo'],
      ['びょ', 'byo', 'bʲo'],
      ['ぴょ', 'pyo', 'pʲo'],
      ['きゃ', 'kya', 'kʲa'],
      ['しゃ', 'sha', 'ɕa'],
      ['ちゃ', 'cha', 'tɕa'],
      ['にゃ', 'nya', 'ɲa'],
      ['ひゃ', 'hya', 'ça'],
      ['みゃ', 'mya', 'mʲa'],
      ['きゅ', 'kyu', 'kʲɯ'],
      ['しゅ', 'shu', 'ɕɯ'],
      ['ちゅ', 'chu', 'tɕɯ'],
      ['にゅ', 'nyu', 'ɲɯ'],
      ['ひゅ', 'hyu', 'çɯ'],
      ['みゅ', 'myu', 'mʲɯ'],
      ['きょ', 'kyo', 'kʲo'],
      ['しょ', 'sho', 'ɕo'],
      ['ちょ', 'cho', 'tɕo'],
      ['にょ', 'nyo', 'ɲo'],
      ['ひょ', 'hyo', 'ço'],
      ['みょ', 'myo', 'mʲo'],
      ['りゃ', 'rya', 'ɾʲa'],
      ['りゅ', 'ryu', 'ɾʲɯ'],
      ['りょ', 'ryo', 'ɾʲo'],
      ['ん', 'n', 'n']
    ]
  },
  language: undefined
  // active_letters:[],
  // active_words:[],
  // nav_message:'Select Language',
  // active_language:'',
  // active_character_set:'',
  // language_character_set_map:{
  //   'japanese':[{
  //     value:'hiragana',
  //     label:'Hiragana',
  //     translated_label:'ひらがな',
  //   },{
  //     value:'katakana',
  //     label:'Katakana',
  //     translated_label:'かたかな',
  //   }],
  //   'hebrew':[{
  //     value: 'modern_hebrew',
  //     label: 'Modern Hebrew',
  //     translated_label:'עִברִית',
  //   }],
  //   'arabic':[{
  //     value:'modern_arabic',
  //     label:'Modern_Arabic',
  //     translated_label:'عربى',
  //   }]
  // },
  // all_languages:[{
  //   label:'Japanese',
  //   translated_label:'にほん',
  //   icon:'search',
  //   value:'japanese',
  //   force:false,
  // },{
  //   label:'Hebrew',
  //   translated_label:'עִברִית',
  //   icon:'search',
  //   value:'hebrew',
  //   force:true,
  // },{
  //   label:'Arabic',
  //   translated_label:'عربى',
  //   icon:'search',
  //   value:'arabic',
  //   force:false,
  // }],
  // words_map_by_language:{
  //   'japanese':{
  //     "hiragana":{
  //       "color":[{"english":"red","char_ind_arr":[0,1]},{"english":"blue/green","char_ind_arr":[0,37]},{"english":"yelow","char_ind_arr":[11,10,45]},{"english":"white","char_ind_arr":[12,45]},
  //         {"english":"black","char_ind_arr":[20,45]},{"english":"dark blue","char_ind_arr":[38,108]},{"english":"light blue","char_ind_arr":[16,58,10,45]},{"english":"green","char_ind_arr":[16,69,17]},
  //         {"english":"purple","char_ind_arr":[25,8,2,11]},
  //         {"english":"orange","char_ind_arr":[37,8,108,62]},{"english":"pink","char_ind_arr":[56,108,20]},{"english":"brown","char_ind_arr":[89,10,45]},{"english":"grey","char_ind_arr":[5,10,10,45]},
  //         {"english":"gold","char_ind_arr":[11,108,10,45]},{"english":"silver","char_ind_arr":[52,108,10,45]}],
  //       "animal":[{"english":"cat","char_ind_arr":[32,38]},{"english":"rat / mouse","char_ind_arr":[32,58,16]},{"english":"donkey","char_ind_arr":[45,50]},{"english":"pig","char_ind_arr":[60,3]},{"english":"horse","char_ind_arr":[19,6]},
  //         {"english":"chicken","char_ind_arr":[14,9,40,17]},{"english":"goose","char_ind_arr":[47,101,19]},{"english":"wild duck","char_ind_arr":[1,43]},{"english":"domestic duck","char_ind_arr":[0,15,27]},
  //         {"english":"sheep","char_ind_arr":[15,22,53]},{"english":"cow","char_ind_arr":[19,12]},{"english":"hamster","char_ind_arr":[5,25,21,3]},
  //         {"english":"dog","char_ind_arr":[10,23]},{"english":"deer","char_ind_arr":[12,1]},{"english":"rabbit","char_ind_arr":[19,2,52]},{"english":"giraffe","char_ind_arr":[11,17,108]},
  //         {"english":"camel","char_ind_arr":[8,20,49]},{"english":"hump","char_ind_arr":[38,60]},{"english":"elephant","char_ind_arr":[68,19]},{"english":"panda","char_ind_arr":[51,108,49]},
  //         {"english":"kangaroo","char_ind_arr":[1,108,47,27]},{"english":"leopard / panther","char_ind_arr":[103,19]},{"english":"fox","char_ind_arr":[11,22,32]},{"english":"lion","char_ind_arr":[8,10,37,108]},
  //         {"english":"tiger","char_ind_arr":[40,8]},{"english":"\"crocodile /","char_ind_arr":[9,14]},{"english":"hippopotamus","char_ind_arr":[1,50]},{"english":"bear","char_ind_arr":[20,6]},
  //         {"english":"wolf","char_ind_arr":[37,37,1,16]},{"english":"monkey","char_ind_arr":[2,27]},{"english":"raccoon dog","char_ind_arr":[3,23,11]},{"english":"gorilla","char_ind_arr":[67,17,8]},
  //         {"english":"zebra","char_ind_arr":[12,6,19,6]},{"english":"ostrich","char_ind_arr":[49,101,19]},
  //         {"english":"boar","char_ind_arr":[10,41,12,12]},{"english":"rhino","char_ind_arr":[2,10]},{"english":"horn","char_ind_arr":[22,41]},{"english":"snake","char_ind_arr":[33,55]},
  //         {"english":"chameleon","char_ind_arr":[1,34,35,37,108]},{"english":"gecko","char_ind_arr":[7,43,17]},{"english":"snail","char_ind_arr":[1,3,22,25,17]},{"english":"lizard","char_ind_arr":[40,1,62]},
  //         {"english":"tortoise / turtle","char_ind_arr":[1,34]},{"english":"shell","char_ind_arr":[38,19,8]},{"english":"bat","char_ind_arr":[38,19,43,17]},{"english":"chimpanzee","char_ind_arr":[13,108,51,108,53]},
  //         {"english":"koala","char_ind_arr":[38,0,8]},{"english":"polar bear","char_ind_arr":[12,45,20,6]},{"english":"anteater","char_ind_arr":[0,17,20,10]},{"english":"platypus","char_ind_arr":[1,43,41,5,12]},
  //         {"english":"raccoon","char_ind_arr":[0,8,10,57,6]},{"english":"porcupine","char_ind_arr":[7,6,0,8,12]},{"english":"squirrel","char_ind_arr":[17,21]},{"english":"goat","char_ind_arr":[7,52]},
  //         {"english":"pangolin","char_ind_arr":[30,108,48,108,38,19]}]
  //     },
  //   },
  //   "hebrew":{
  //     "modern_hebrew":{
  //       "color":[{"english":"Blue","char_ind_arr":[12,8,6,14],"sound":"cachol"},
  //       {"english":"Black","char_ind_arr":[30,8,6,26],"sound":"shachor"},{"english":"Red","char_ind_arr":[0,4,6,16],"sound":"edom"},
  //       {"english":"Purple","char_ind_arr":[19,3,6,14],"sound":"segol"},{"english":"Yellow","char_ind_arr":[24,5,6,2],"sound":"tzahov"},
  //       {"english":"Green","char_ind_arr":[10,26,6,25],"sound":"yarok"},{"english":"Orange","char_ind_arr":[12,29,6,16],"sound":"catom"},
  //       {"english":"Rose","char_ind_arr":[6,26,4],"sound":"vered"},{"english":"Grey","char_ind_arr":[0,22,6,26],"sound":"afor"},
  //       {"english":"Brown","char_ind_arr":[8,6,16],"sound":"chom"},{"english":"White","char_ind_arr":[14,2,18],"sound":"lavan"},
  //       {"english":"Light Blue","char_ind_arr":[29,12,14,29],"sound":"techelet"},{"english":"Dark Blue","char_ind_arr":[12,8,6,14,-10,12,5,5],"sound":"cachol cehe"},
  //       {"english":"Cream","char_ind_arr":[25,26,16],"sound":"crem"}]
  //     }
  //   }
  // },
  // letters_map_by_language:{
  //   'japanese': {
  //     "hiragana":[["あ","a","a"],["か","ka","ka"],["さ","sa","sa"],["た","ta","ta"],["な","na","na"],["は","ha","ha"],["ま","ma","ma"],["や","ya","ja"],["ら","ra","ɾa"],["わ","wa","ɰa"],["い","i","i"],["き","ki","ki"],["し","shi","ɕi"],["ち","chi","tɕi"],["に","ni","ɲi"],["ひ","hi","çi"],["み","mi","mi"],["り","ri","ɾi"],["ゐ","wi","i"],["う","u","ɯ"],["く","ku","kɯ"],["す","su","sɯ"],["つ","tsu","tsɯ"],["ぬ","nu","nɯ"],["ふ","fu","ɸɯ"],["む","mu","mɯ"],["ゆ","yu","jɯ"],["る","ru","ɾɯ"],["え","e","e"],["け","ke","ke"],["せ","se","se"],["て","te","te"],["ね","ne","ne"],["へ","he","he"],["め","me","me"],["れ","re","ɾe"],["ゑ","we","e"],["お","o","o"],["こ","ko","ko"],["そ","so","so"],["と","to","to"],["の","no","no"],["ほ","ho","ho"],["も","mo","mo"],["よ","yo","jo"],["ろ","ro","ɾo"],["を","wo","o"],["が","ga","ɡa"],["ざ","za","za"],["だ","da","da"],["ば","ba","ba"],["ぱ","pa","pa"],["ぎ","gi","ɡi"],["じ","ji","ʑi"],["ぢ","ji","dji"],["び","bi","bi"],["ぴ","pi","pi"],["ぐ","gu","ɡɯ"],["ず","zu","zɯ"],["づ","dzu","zu"],["ぶ","bu","bɯ"],["ぷ","pu","pɯ"],["げ","ge","ɡe"],["ぜ","ze","ze"],["で","de","de"],["べ","be","be"],["ぺ","pe","pe"],["ご","go","ɡo"],["ぞ","zo","zo"],["ど","do","do"],["ぼ","bo","bo"],["ぽ","po","po"],["ぎゃ","gya","ɡʲa"],["じゃ","ja","ʑa"],["ぢゃ","ja","ʑa"],["びゃ","bya","bʲa"],["ぴゃ","pya","pʲa"],["ぎゅ","gyu","ɡʲɯ"],["じゅ","ju","ʑɯ"],["ぢゅ","ju","ʑɯ"],["びゅ","byu","bʲɯ"],["ぴゅ","pyu","pʲɯ"],["ぎょ","gyo","ɡʲo"],["じょ","jo","ʑo"],["ぢょ","jo","ʑo"],["びょ","byo","bʲo"],["ぴょ","pyo","pʲo"],["きゃ","kya","kʲa"],["しゃ","sha","ɕa"],["ちゃ","cha","tɕa"],["にゃ","nya","ɲa"],["ひゃ","hya","ça"],["みゃ","mya","mʲa"],["きゅ","kyu","kʲɯ"],["しゅ","shu","ɕɯ"],["ちゅ","chu","tɕɯ"],["にゅ","nyu","ɲɯ"],["ひゅ","hyu","çɯ"],["みゅ","myu","mʲɯ"],["きょ","kyo","kʲo"],["しょ","sho","ɕo"],["ちょ","cho","tɕo"],["にょ","nyo","ɲo"],["ひょ","hyo","ço"],["みょ","myo","mʲo"],["りゃ","rya","ɾʲa"],["りゅ","ryu","ɾʲɯ"],["りょ","ryo","ɾʲo"],["ん","n","n"]],
  //     'katakana':[
  //       ['ア','a','a'],  //       ['カ','ka','ka'],  //       ['サ','sa','sa'],  //       ['タ','ta','ta'],  //       ['ナ','na','na'],  //       ['ハ','ha','ha'],  //       ['マ','ma','ma'],  //       ['ヤ','ya','ja'],  //       ['ラ','ra','ɾa'],  //       ['ワ','wa','ɰa'],  //       ['ガ','ga','ɡa'],  //       ['ザ','za','za'],  //       ['ダ','da','da'],  //       ['バ','ba','ba'],  //       ['パ','pa','pa'],  //     ]
  //   },
  //   "hebrew":{
  //     "modern_hebrew":[
  //       [`א`,``,''],
  //       [`בּ`,`b`,``],[`ב`,`v`,``],[`ג`,`g`,``],[`ד`,`d`,``],[`ה`,`h`,``],[`ו`,`v`,``],[`ז`,`z`,``],
  //       [`ח`,`kh`,``],[`ט`,`t`,``],[`י`,`y`,``],[`כּ`,`k`,``],[`כ`,`kh`,``],[`ך`,`kh`,``],
  //       [`ל`,`l`,``],[`מ`,`m`,``],[`ם`,`m`,``],[`נ`,`n`,``],[`ן`,`n`,``],[`ס`,`s`,``],[`ע`,``,``]
  //       ,[`פּ`,`p`,``],[`פ`,`ph`,``],[`ף`,`ph`,``],[`צ`,`ts`,``],[`ק`,`k`,``],[`ר`,`r`,``],[`שׁ`,`sh`,``],
  //       [`שׂ`,`s`,``],
  //       [`ת`,`t`,``],["ש","s",""]
  //     ]
  //   // 'hebrew': {
  //   //   'modern_hebrew':[
  //   //     ['א','aleph'],  //   //     ['ב','bet'],  //   //     ['ב','vet'],  //   //     ['ג','gimmel'],  //   //     ['ד','dalet'],  //   //     ['ה','he'],  //   //     ['ו','vav'],  //   //     ['ז','zayin'],  //   //     ['ח','khet'],  //   //     ['ט','tet'],  //   //     ['י','yud'],  //   //     ['כּ','kaf'],  //   //     ['כ','khaf'],  //   //     ['ך','khaf sofit'],  //   //     ['ל','lamed'],  //   //     ['מ','mem'],  //   //     ['ם','mem sofit'],  //   //     ['נ','nun'],  //   //     ['ן','nun sofit'],  //   //     ['ס','samech'],  //   //     ['ע','ayin'],  //   //     ['פ','pe'],  //   //     ['פ','phe'],  //   //     ['ף','phe sofit'],  //   //     ['צ','tsadi'],  //   //     ['ק','quf'],  //   //     ['ר','resh'],  //   //     ['שׁ','shin'],  //   //     ['שׂ','sin'],  //   //     ['ת','tav'],  //   //   ]
  //   },
  //   'arabic':{
  //     'modern_arabic':[
  //       ['ي','y'],  //       ['و','w'],  //       ['ه','h'],  //       ['ش','sh'],  //       ['س','s'],  //       ['ق','q'],  //       ['ف','f'],  //       ['غ','gh'],  //       ['ع','ʿ'],  //       ['ض','ḍ'],  //       ['ص','ṣ'],  //       ['ن','n'],  //       ['م','m'],  //       ['ل','l'],  //       ['ك','k'],  //       ['ظ','ẓ'],  //       ['ط','ṭ'],  //       ['ز','z'],  //       ['ر','r'],  //       ['ذ','dh'],  //       ['د','d'],  //       ['خ','kh'],  //       ['ح','ḥ'],  //       ['ج','j'],  //       ['ث','th'],  //       ['ت','t'],  //       ['ب','b'],  //       ['ا','ā'],  //     ]
  //   }
  // },
}
